version: "3.3"
services:
  postgres:
    image: postgres:12
    container_name: openhabitation-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${DATABASE}
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - ./database/:/var/lib/postgresql/
  api:
    build:
      context: .
    depends_on:
      - postgres
    container_name: openhabitation-api
    tty: true # docker run -d
    stdin_open: true # docker run -i
    networks:
      - default
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE}
    ports:
      - 8000:8000


